project_id = "ejmqntdcjbzseovoivnu"
[functions.seed-test-users]
verify_jwt = false

[functions.geocode-units]
verify_jwt = false

[functions.daily-huddle-reminders]
verify_jwt = false

[functions.commitments-reminders]
verify_jwt = false

[functions.calculate-achievements]
verify_jwt = false

[functions.tv-feed]
verify_jwt = false

[functions.generate-daily-briefing]
verify_jwt = false
